"""Deterministic field extraction from Amrita Hospital billing PDFs.

Two document types are supported, both generated by the same hospital
billing system with a fixed template:

* **Estimate Performa**   -> :func:`extract_estimate_performa`
* **Summary Bill (IP Bill)** -> :func:`extract_summary_bill`

Only page 1 of each PDF is read; annexure / later pages are ignored.

How it works
------------
``page.extract_text(layout=True)`` renders the page as monospaced text that
keeps the two-column label block aligned, e.g.::

     M R D Number : 317251                   Patient Name : ALAALDEN KHALIFA
                                                          OSMAN ALTAHER
     Admitting Doctor : Anil Kumar Murarka   Duration of Stay : 2

Each field is then found with a label-anchored regex, line by line. A value
runs from just after ``<label> :`` up to the next *known label on the same
line* (the right-hand column) or the end of the line. No fixed coordinates
are used, so small layout shifts between documents are tolerated.

A field whose label is absent (or whose value is empty / in the wrong
format) is returned as ``None`` and its name is appended to the
``missing_fields`` list in the result, so the caller can flag incomplete
extractions instead of catching exceptions.

Patching for template changes
-----------------------------
Every label the parsers rely on is declared in ``_ESTIMATE_LABELS`` /
``_BILL_LABELS`` below, and each extractor's docstring lists the exact label
text expected per field. If the hospital renames a label, update the regex in
the relevant table; if it adds a new label to the right-hand column, add it
there too so it terminates the value to its left.

No network or AI/LLM calls are made -- this is pure text/regex extraction.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pdfplumber

# --------------------------------------------------------------------------
# Label tables (regex fragments). Keys are internal names; values match the
# label text as printed, tolerant of extra spacing.
# --------------------------------------------------------------------------

_ESTIMATE_LABELS = {
    "mrd_number": r"M\s*R\s*D\s*Number",
    "patient_name": r"Patient\s+Name",
    "admitting_doctor": r"Admitting\s+Doctor",
    "duration_of_stay": r"Duration\s+of\s+Stay",
    "speciality": r"Speciality",
    "expected_doa": r"Expected\s+D\.O\.A",
    "bed_type": r"Bed\s+Type",
    "estimation_label": r"Estimation",
}

_BILL_LABELS = {
    "mrd_number": r"M\s*R\s*D\s*Number",
    # "Patient :" appears twice on the bill: the name (same line as MRD
    # Number) and the address ("Patient :<address>" with "Address" wrapped
    # below). The name lookup is therefore restricted to the MRD line.
    "patient_name": r"Patient",
    "visit_number": r"Visit\s+Number",
    "category": r"Category",
    "admitting_doctor": r"Admitting\s+Doctor",
    "doa": r"D\.O\.A",
    "dod": r"D\.O\.D",
    # Right-hand-column labels that are not extracted but must terminate the
    # value of the left-hand label on the same line.
    "_patient_age": r"Patient\s+Age",
    "_cell_phone": r"Cell\s+Phone",
    "_speciality": r"Speciality",
    "_payer": r"Payer",
    "_date": r"Date",
    "_bed": r"Bed",
    "_sponsor": r"Sponsor",
}

_DATE = r"\d{2}/\d{2}/\d{4}"
_DATETIME = r"\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}"
# An amount, optionally prefixed with "Rs." / "Rs" / "₹", with optional
# thousands separators and decimals.
_AMOUNT = r"(?:Rs\.?\s*|₹\s*)?-?[\d,]+(?:\.\d+)?"

ESTIMATE_MARKERS = ("ESTIMATE PERFORMA",)
BILL_MARKERS = ("IN PATIENT COLLECTION & APPROPRIATION", "IN-PATIENT SUMMARY BILL")


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def _read_page1_layout(pdf_path) -> str:
    """Return the layout-preserving text of page 1 only ('' if no pages)."""
    with pdfplumber.open(pdf_path) as pdf:
        if not pdf.pages:
            return ""
        return pdf.pages[0].extract_text(layout=True) or ""


def _collapse(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _parse_amount(raw: str | None) -> float | None:
    """'Rs. 2,54,310.00' -> 254310.0. Returns None if nothing numeric remains."""
    if raw is None:
        return None
    cleaned = re.sub(r"Rs\.?|₹|,|\s", "", raw)
    try:
        return float(cleaned)
    except ValueError:
        return None


def _stop_lookahead(labels: dict) -> str:
    """Lookahead that ends a value at the next known '<label> :' or EOL."""
    alts = "|".join(labels.values())
    return rf"(?=\s+(?:{alts})\s*:|\s*$)"


def _find_label_value(lines, label_re, stop, value_re=r".*?", only_line=None):
    """Find '<label> : <value>' on a single line.

    Returns (value, line_index, value_column) or None. ``value_column`` is the
    character offset where the value starts in the layout text, used to
    detect wrapped continuation lines.
    """
    pattern = re.compile(
        rf"(?<![A-Za-z]){label_re}\s*:\s*(?P<v>{value_re}){stop}"
    )
    indices = [only_line] if only_line is not None else range(len(lines))
    for i in indices:
        m = pattern.search(lines[i])
        if m:
            value = m.group("v").strip()
            return (value or None), i, m.start("v")
    return None


def _append_wrapped(lines, line_idx, value_col, value, max_extra=2):
    """Join continuation lines of a wrapped right-column value.

    A following line counts as a continuation when everything left of the
    value's column is blank (so it is not a left-column field), it is
    non-empty, and it contains no ':' (so it is not another label).
    """
    parts = [value]
    tolerance = 2
    for j in range(line_idx + 1, min(line_idx + 1 + max_extra, len(lines))):
        nxt = lines[j]
        left, right = nxt[: max(value_col - tolerance, 0)], nxt[max(value_col - tolerance, 0):]
        if left.strip() or not right.strip() or ":" in nxt:
            break
        parts.append(right.strip())
    return _collapse(" ".join(parts))


def _pick_column_amount(line: str, header_line: str | None, header_re: str):
    """From a row with several amounts, pick the one under ``header_re``.

    Amounts are right-aligned under their column header, so the amount whose
    right edge is closest to the header's right edge wins. Falls back to the
    first amount on the line when the header is not found.
    """
    matches = list(re.finditer(_AMOUNT, line))
    matches = [m for m in matches if re.search(r"\d", m.group())]
    if not matches:
        return None
    if header_line:
        h = re.search(header_re, header_line)
        if h:
            return min(matches, key=lambda m: abs(m.end() - h.end())).group()
    return matches[0].group()


def _finalize(fields: dict, order: list[str]) -> dict:
    fields["missing_fields"] = [k for k in order if fields.get(k) is None]
    return fields


# --------------------------------------------------------------------------
# Text-level parsers (pure functions; unit-testable without a PDF)
# --------------------------------------------------------------------------

ESTIMATE_FIELDS = [
    "mrd_number", "patient_name", "admitting_doctor", "speciality",
    "duration_of_stay", "expected_doa", "bed_type", "estimation_label",
    "total_estimate",
]

BILL_FIELDS = [
    "mrd_number", "patient_name", "visit_number", "category",
    "admitting_doctor", "doa", "dod", "total_billed", "net_amount_due",
]


def parse_estimate_text(text: str) -> dict:
    """Parse the page-1 layout text of an Estimate Performa. See
    :func:`extract_estimate_performa` for the field/label contract."""
    lines = text.split("\n")
    stop = _stop_lookahead(_ESTIMATE_LABELS)
    L = _ESTIMATE_LABELS
    out: dict = {}

    def simple(key, value_re=r".*?"):
        hit = _find_label_value(lines, L[key], stop, value_re)
        return hit[0] if hit else None

    out["mrd_number"] = simple("mrd_number", r"\S+")

    hit = _find_label_value(lines, L["patient_name"], stop)
    out["patient_name"] = (
        _append_wrapped(lines, hit[1], hit[2], hit[0]) if hit and hit[0] else None
    )

    out["admitting_doctor"] = simple("admitting_doctor")
    out["speciality"] = simple("speciality")
    out["duration_of_stay"] = simple("duration_of_stay")
    out["expected_doa"] = simple("expected_doa", _DATE)
    out["bed_type"] = simple("bed_type")
    out["estimation_label"] = simple("estimation_label")

    for k in ("admitting_doctor", "speciality", "bed_type", "estimation_label"):
        if out[k] is not None:
            out[k] = _collapse(out[k])

    m = re.search(rf"^\s*Total\s+Estimate\s*:?\s*({_AMOUNT})\s*$", text, re.MULTILINE)
    out["total_estimate"] = _parse_amount(m.group(1)) if m else None

    return _finalize(out, ESTIMATE_FIELDS)


def parse_summary_bill_text(text: str) -> dict:
    """Parse the page-1 layout text of a Summary Bill. See
    :func:`extract_summary_bill` for the field/label contract."""
    lines = text.split("\n")
    stop = _stop_lookahead(_BILL_LABELS)
    L = _BILL_LABELS
    out: dict = {}

    def simple(key, value_re=r".*?", only_line=None):
        hit = _find_label_value(lines, L[key], stop, value_re, only_line)
        return hit[0] if hit else None

    mrd_hit = _find_label_value(lines, L["mrd_number"], stop, r"\S+")
    out["mrd_number"] = mrd_hit[0] if mrd_hit else None

    # Patient name: only on the MRD Number line (the address shares the label).
    # The "Patient Age" label is excluded by requiring ':' right after "Patient".
    out["patient_name"] = None
    if mrd_hit:
        hit = _find_label_value(lines, L["patient_name"], stop, only_line=mrd_hit[1])
        if hit and hit[0]:
            out["patient_name"] = _append_wrapped(lines, hit[1], hit[2], hit[0])

    out["visit_number"] = simple("visit_number", r"\S+")
    out["category"] = simple("category")
    out["admitting_doctor"] = simple("admitting_doctor")
    out["doa"] = simple("doa", _DATETIME)
    out["dod"] = simple("dod", _DATETIME)

    for k in ("category", "admitting_doctor", "doa", "dod"):
        if out[k] is not None:
            out[k] = _collapse(out[k])

    # "Total :" row of the Summary of Transactions; Charges(Rs) column.
    header = next((ln for ln in lines if re.search(r"Charges\s*\(Rs\)", ln)), None)
    total_line = next(
        (ln for ln in lines if re.match(rf"^\s*Total\s*:\s*{_AMOUNT}", ln)), None
    )
    out["total_billed"] = (
        _parse_amount(_pick_column_amount(total_line, header, r"Charges\s*\(Rs\)"))
        if total_line else None
    )

    m = re.search(rf"Net\s+Amount\s+Due\s*\(Rs\.?\)\s*:?\s*({_AMOUNT})", text)
    out["net_amount_due"] = _parse_amount(m.group(1)) if m else None

    return _finalize(out, BILL_FIELDS)


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------

def extract_estimate_performa(pdf_path) -> dict:
    """Extract fields from page 1 of an Amrita *Estimate Performa* PDF.

    Expected labels (as printed on page 1, two-column block at the top):

    ================  ===================================  ==================
    Field             Label                                Value format
    ================  ===================================  ==================
    mrd_number        ``M R D Number :``                   single token
    patient_name      ``Patient Name :``                   free text; may wrap
                                                           onto the next line
                                                           (joined, whitespace
                                                           collapsed)
    admitting_doctor  ``Admitting Doctor :``               free text
    speciality        ``Speciality :``                     free text
    duration_of_stay  ``Duration of Stay :``               text (e.g. ``2``)
    expected_doa      ``Expected D.O.A :``                 ``DD/MM/YYYY``
    bed_type          ``Bed Type :``                       free text
    estimation_label  ``Estimation :``                     e.g. ``Estimation 2``
    total_estimate    row ``Total Estimate`` at the foot   float (commas /
                      of the "Estimated Expenditure"       ``Rs.`` stripped)
                      table
    ================  ===================================  ==================

    Individual line items of the Estimated Expenditure table are not parsed.

    Returns a dict with the keys above plus ``missing_fields`` (list of field
    names that came back ``None``), ``source_file`` and ``document_type``.
    Never raises for a missing label.
    """
    result = parse_estimate_text(_read_page1_layout(pdf_path))
    result["source_file"] = Path(pdf_path).name
    result["document_type"] = "estimate_performa"
    return result


def extract_summary_bill(pdf_path) -> dict:
    """Extract fields from page 1 of an Amrita *Summary Bill* (IP Bill) PDF.

    Page 1 is headed "In Patient Collection & Appropriation" (or "In-Patient
    Summary Bill"). Annexure pages are ignored.

    Expected labels (as printed on page 1):

    ================  ===================================  ==================
    Field             Label                                Value format
    ================  ===================================  ==================
    mrd_number        ``M R D Number :``                   single token
    patient_name      ``Patient :`` **on the same line as  free text
                      M R D Number** (a second
                      ``Patient :`` further down holds
                      the address and is ignored)
    visit_number      ``Visit Number :``                   single token
    category          ``Category :``                       free text
    admitting_doctor  ``Admitting Doctor :``               free text
    doa               ``D.O.A :``                          ``DD/MM/YYYY HH:MM``
    dod               ``D.O.D :``                          ``DD/MM/YYYY HH:MM``
    total_billed      row ``Total :`` in "Summary of       float; the amount
                      Transactions"                        under the
                                                           ``Charges(Rs)``
                                                           header (not
                                                           Credits)
    net_amount_due    row ``Net Amount Due (Rs)``          float
    ================  ===================================  ==================

    Returns a dict with the keys above plus ``missing_fields``,
    ``source_file`` and ``document_type``. Never raises for a missing label.
    """
    result = parse_summary_bill_text(_read_page1_layout(pdf_path))
    result["source_file"] = Path(pdf_path).name
    result["document_type"] = "summary_bill"
    return result


def detect_document_type(pdf_path) -> str | None:
    """Return 'estimate_performa', 'summary_bill' or None, based on page-1
    heading text (whitespace-normalised, case-insensitive)."""
    page_text = _collapse(_read_page1_layout(pdf_path)).upper()
    if any(mk in page_text for mk in ESTIMATE_MARKERS):
        return "estimate_performa"
    if any(mk in page_text for mk in BILL_MARKERS):
        return "summary_bill"
    return None


def extract_any(pdf_path) -> dict:
    """Auto-detect the document type and run the matching extractor.

    If the type cannot be detected, both extractors are run and returned
    under ``estimate_performa`` / ``summary_bill`` keys with
    ``document_type`` set to None.
    """
    doc_type = detect_document_type(pdf_path)
    if doc_type == "estimate_performa":
        return extract_estimate_performa(pdf_path)
    if doc_type == "summary_bill":
        return extract_summary_bill(pdf_path)
    return {
        "document_type": None,
        "source_file": Path(pdf_path).name,
        "estimate_performa": extract_estimate_performa(pdf_path),
        "summary_bill": extract_summary_bill(pdf_path),
    }


def main(argv: list[str]) -> int:
    """CLI: ``python -m app.pdf_extract FILE [FILE ...]``.

    Prints each extraction as JSON. When at least one estimate and one bill
    are given, also reports whether their MRD numbers match.
    """
    if not argv:
        print("usage: python -m app.pdf_extract FILE.pdf [FILE.pdf ...]", file=sys.stderr)
        return 2

    results = [extract_any(p) for p in argv]
    payload = results[0] if len(results) == 1 else {"documents": results}

    estimates = [r for r in results if r.get("document_type") == "estimate_performa"]
    bills = [r for r in results if r.get("document_type") == "summary_bill"]
    if estimates and bills:
        payload["mrd_reconciliation"] = [
            {
                "estimate": e["source_file"],
                "bill": b["source_file"],
                "estimate_mrd": e["mrd_number"],
                "bill_mrd": b["mrd_number"],
                "mrd_match": e["mrd_number"] is not None
                and e["mrd_number"] == b["mrd_number"],
            }
            for e in estimates for b in bills
        ]

    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
